# Doctrine Configuration
doctrine:
    orm:
        dql:
            string_functions:
                jsonbbykey: fabianofa\JsonbOperatorsBundle\Doctrine\Query\JsonbByKey
                jsonbbykeytext: fabianofa\JsonbOperatorsBundle\Doctrine\Query\JsonbByKeyText
                jsonbbypath: fabianofa\JsonbOperatorsBundle\Doctrine\Query\JsonbByPath